version: '3.8'

services:
  postgres:
    container_name: school_software_pg
    image: postgres
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${USER}
      POSTGRES_PASSWORD: ${PASSWORD}
      POSTGRES_DB: ${DATABASE}
      PGDATA: /data/postgres
    volumes:
      - ./data/pg:/data/postgres
